#analyzer:
#  strong-mode: true
#   exclude:
#     - path/to/excluded/files/**

analyzer:
  exclude:
    #- test/_data/p4/lib/lib1.dart
    #- test/_data/p5/p5.dart
    #- test/_data/bad*.dart
    #- test/_brokendata/**
    - db/**

# Lint rules and documentation, see

linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps