name: auge_server
description: A web server built using the shelf package.
version: 0.0.1
# homepage: https://www.example.com
# author: Samuel <email@example.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  args: ^1.5.0
  intl: ^0.15.7
  shelf: ^0.7.3+3
  rpc: ^0.6.0
  postgres: ^1.0.0
  uuid: ^1.0.1
  http: ^0.11.3+17
  _discoveryapis_commons: ^0.1.6+1

dev_dependencies:
  test: ^1.3.0