name: auge_server
description: A web server built using the shelf package.
version: 0.0.1
# homepage: https://www.example.com
# author: Samuel <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.0
  intl: ^0.15.7
  shelf: ^0.7.3+3
  rpc: ^0.6.0
  fixnum: ^0.10.9
  #rpc:
  #  git:
  #    url: git://github.com/dart-archive/rpc.git
  #    ref: experimental-mirrors-refactor
  #protobuf: ^0.13.9
  #grpc: ^1.0.2
  #grpc:
  #  git:
  #    url: git://github.com/grpc/grpc-dart.git
  #    ref: master
      #url: git://github.com/dart-archive/rpc.git
      #ref: experimental-mirrors-refactor
  protoc_plugin: ^16.0.5
  postgres: ^1.0.2
  uuid: ^2.0.0-rc1
  http: ^0.12.0
  http2: ^1.0.0
  _discoveryapis_commons: ^0.1.8+1


dev_dependencies:
  test: ^1.3.0

dependency_overrides:
  protobuf: ^0.13.9
  grpc:
    git:
      url: git://github.com/grpc/grpc-dart.git
      ref: grpc-web
