name: auge_server
description: A web server built using the shelf package.
version: 0.0.1
# homepage: https://www.example.com
# author: Samuel <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  #args: ^1.5.0
  intl: ^0.15.7
  #shelf: ^0.7.3+3
  #rpc: ^0.6.0
  fixnum: ^0.10.9
  #rpc:
  #  git:
  #    url: git://github.com/dart-archive/rpc.git
  #    ref: experimental-mirrors-refactor
  #protobuf: ^0.13.9
  #grpc: ^1.0.2
  #grpc:
  #  git:
  #    url: git://github.com/grpc/grpc-dart.git
  #    ref: master
      #url: git://github.com/dart-archive/rpc.git
      #ref: experimental-mirrors-refactor
  protoc_plugin: 17.0.2
  postgres: ^1.0.2
  uuid: ^2.0.2
  #http: ^0.12.0
  #http2: ^1.0.0
  #_discoveryapis_commons: ^0.1.8+1
  protobuf: ^0.13.12
  grpc: ^2.0.0+1
  dartdap: ^0.3.5
  #grpc:
  #  git:
  #    url: git://github.com/grpc/grpc-dart.git
  #    ref: grpc-web
  #grpc:
  #  git:
  #    url: git://github.com/sigurdm/grpc-dart.git
  #    ref: ff07ddeae8dcae519b848a9d869dad9724a3ed42

dev_dependencies:
  test: ^1.6.3

dependency_overrides:
  #protobuf: ^0.13.11
  #grpc:
  #  git:
  #    url: git://github.com/grpc/grpc-dart.git
  #    ref: grpc-web