name: auge_server
description: A web server built using the shelf package.
version: 0.0.1
# homepage: https://www.example.com
# author: Samuel <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.0
  intl: ^0.15.7
  shelf: ^0.7.3+3
  rpc: ^0.6.0
  postgres: ^1.0.2
  uuid: ^1.0.3
  http: ^0.11.0
  _discoveryapis_commons: ^0.1.8+1

dev_dependencies:
  test: ^1.3.0