database:
  host: 'host.docker.internal'
  port: 5432
  databaseName: 'auge'
  username: 'postgres'
  password: 'admin@levius#2018'
mail:
  baseURL: ''
  clientID: 'levius@levius.com.br'
  clientSecret: 'kegtbariprhileon'