version: '3'
services:
  auge-server:
    volumes:
      - /d/Levius/IdeaProjects/auge_server:/auge_server
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/auge_server/Dockerfile
    ports:
      - "9091:9091"
  envoy:
    build:
      context: ./
      dockerfile: ./net/grpc/gateway/docker/envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
    links:
      - auge-server

       